{% set name = "lbcommon" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbCommon-{{ version }}.tar.gz
  sha256: e8c878dc0459e9f8144068f4f04d1a685a2b13b4ebeb2e1dc35499c3b44768bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.2
    - nose >=1.0
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - LbCommon
    - LbCommon.CMake
    - LbCommon.ConfigFile
    - LbCommon.Env
    - LbCommon.Log
    - LbCommon.Option
    - LbCommon.Processes
    - LbCommon.Script
    - LbCommon.Temporary
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/LbCommon
  summary: LHCb Common tools
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
